/* kardinal/evaluate.c
*  Omkar H. Ramachandran
*  omkar.ramachandran@colorado.edu
*
*  Main script parser/logic interface of the game. Do not edit this file unless 
*  absolutely necessary
* 
*
*  This project is under the GNU General GPL version 3.0 license. For more 
*  information about the license, refer the LICENCE file in the root directory 
*  or go online to <http://www.gnu.org/licenses>
*  
*  Any redistribution of this code must contain this header in its entirety
*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "kardinal.h"

int evaluate(Input * In, Input * args, int size_args){
/* Dummy evaluate function. Must be updated in the next few iterations. 
* Perhaps a starting project for NearlyHeadless?
* At present, it just prints out args and seems to work fine. See debug.txt
* -- Tyronst
*/
	printf("Debug : Entered Evaluate\n");
	print(*args);
	strcpy(In->name,"Result");
	In->type = 0;
	printf("Debug : Leaving Evaluate\n");
	return 0;
}

