/* kardinal/evaluate.c
*  Omkar H. Ramachandran
*  omkar.ramachandran@colorado.edu
*
*  Main script parser/logic interface of the game. Do not edit this file unless 
*  absolutely necessary
* 
*
*  This project is under the GNU General GPL version 3.0 license. For more 
*  information about the license, refer the LICENCE file in the root directory 
*  or go online to <http://www.gnu.org/licenses>
*  
*  Any redistribution of this code must contain this header in its entirety
*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "kardinal.h"

int evaluate(Input * In, Input * args, int size_args){
/* Dummy evaluate function. Must be updated in the next few iterations. 
* Perhaps a starting project for NearlyHeadless?
* At present, it does 'all' (universal and), 'one' (exactly one true) and 'not' 
* - seems to work fine, although we need to come up with test cases that
* account for all possible corner cases. See debug.txt
* -- OHR
*/
	char a[20] = "Result_";
	printf("Debug : Entered Evaluate\n");
	printf("Debug : Printing arguments\n");
	print(*args);
	In->type = 0;
	if(strcmp(In->name,"all")==0){
		printf("Debug : Command is 'all'\n");
		int flag = 0;
		do{
			if(strcmp(args->name,"true")!=0){
				flag++;
				printf("Debug : %s is not true\n",args->name);
				strcpy(In->name,"false");
				break;
			}
			args = args->prev;
		}while(args!=NULL);
		if(flag==0){
			strcpy(In->name,"true");	
		}
		printf("Debug : Flag=%d, In.name=%s\n",flag,In->name);
	}else if(strcmp(In->name,"one")==0){
		printf("Debug : Command is 'one'\n");
		int flag = 0;
		do{
			if(strcmp(args->name,"true")==0){
				flag++;
				printf("Debug : %s is true\n",args->name);	
			}
			args = args->prev;	
		}while(args!=NULL);
		if(flag==1){
			strcpy(In->name,"true");	
		}else{
			strcpy(In->name,"false");		
		}
		printf("Debug : Flag=%d, In.name=%s\n",flag,In->name);
	}else if(strcmp(In->name,"not")==0){
/* Note to NearlyHeadless : Do an errorcheck for number of arguments here. 
*  There should be exactly 1 and no more. I'm just spitting out a warning in
*  this version of the code here :
*/
		printf("Debug : Command is 'not'\n");
		if(args->prev!=NULL){
			printf("Warning : Too many arguments. The code will act only on the last argument\n");
		}
		if(strcmp(args->name,"true")==0){
			printf("Debug : arg=%s\n",args->name);
			strcpy(In->name,"false");
		}else if(strcmp(args->name,"false")==0){
			printf("Debug : arg=%s\n",args->name);
			strcpy(In->name,"true");
		}
	// Do an error check here if argument name is neither true or false
		printf("Debug : Arg=%s, In.name=%s\n",args->name,In->name);
	}
	printf("Debug : Leaving Evaluate\n");
	return 0;
}
