/* kardinal/main.c
*  Omkar H. Ramachandran
*  omkar.ramachandran@colorado.edu
*
*  Main script parser/logic interface of the game. Do not edit this file unless 
*  absolutely necessary
* 
*
*  This project is under the GNU General GPL version 3.0 license. For more 
*  information about the license, refer the LICENCE file in the root directory 
*  or go online to <http://www.gnu.org/licenses>
*  
*  Any redistribution of this code must contain this header in its entirety
*/

#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "kardinal.h"

#define MAX_INPUT 256

int TitleSize;
State * Titles;

int main(int argc, char ** argv){
	/* Declarations */
	char line[MAX_INPUT];
//	char input[MAX_INPUT];
	int Fsize;
	State *Player;
	int PlayerSize = 0;
	
	if(argc<3){
		printf("2 input parameters needed!\n");
		exit(1);
	}
	FILE * state_in = fopen(argv[2],"r"),
	     * fin = fopen(argv[1],"r");
	Fsize = getsize(fin);

	
	build_states_test(state_in);
	dump_states_test();
	add_state_to_player(2,&Player,&PlayerSize);
//	printf("Debug : %d %s %d\n",Player[0].id,Player[0].name,Player[0].attribute);
	while(fgets(line,MAX_INPUT,fin)){
		Input *In = (Input *) malloc (sizeof(Input));
	//	In->prev = NULL;
		int i,err,maxlvl;
	// Pretty sure my beautiful conditional operator is no longer necessary
	// :'-( - OHR
		int size_in = (MAX_INPUT>(sizeof(line)))?MAX_INPUT:sizeof(line);
		printf("Debug : Cmd = %s\n\n",line);
/*		for(i=0;i<size_in;i++){
			input[i] = argv[1][i];	
		}
		input[size_in]='\0';
*/
		// Build the command stack
		In = build(In,line);
	//	printf("%s : %d : %d : %s\n\n\n",In->name,In->lvl,In->type,In->prev->name);
		In = parse(In,&Player,&PlayerSize);
		printf("Debug : Command stack after parse\n");
		print(*In);
		printf("\nDebug : Final Result\n");
		print_final(*In);
	//	scanf("%c",&junk);	
		print_player_state(Player,PlayerSize);
		Free(In);
	}	
	free(Titles);
	free(Player);
	fclose(state_in);
	return 0;
}
