/* kardinal/state.c
*  Omkar H. Ramachandran
*  omkar.ramachandran@colorado.edu
*
*  Main script parser/logic interface of the game. Do not edit this file unless 
*  absolutely necessary
* 
*
*  This project is under the GNU General GPL version 3.0 license. For more 
*  information about the license, refer the LICENCE file in the root directory 
*  or go online to <http://www.gnu.org/licenses>
*  
*  Any redistribution of this code must contain this header in its entirety
*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "kardinal.h"

int getsize(FILE * in){
	int N;
	fseek(in,SEEK_SET,0);
	fscanf(in,"size=%d",&N);
	return N;
}

int build_states_test(FILE * in){
/*
*
*
*/
	printf("Debug : Entered build_states_test\n");
	TitleSize = getsize(in);	
	printf("Debug : Survived getsize\n");	
	Titles = (State *) malloc (sizeof(State)*TitleSize);
	printf("Debug : Malloced Titles\n");
	int i=0;

	for(i=0;i<TitleSize;i++){
		int att;
		char name[20];
		fscanf(in,"%s %d",name,&att);
		strcpy(Titles[i].name,name);
		Titles[i].attribute = att;
	}
}

int dump_states_test(){
	int i=0;
	printf("Debug : Dump of global states\n");
	printf("Debug : TitleSize=%d\n",TitleSize);
	for(i=0;i<TitleSize;i++){
		printf("Debug : %s %d\n",Titles[i].name,Titles[i].attribute);
	}
	printf("\n");
	return 0;
}
