/* kardinal/variable.c
*  Omkar H. Ramachandran
*  omkar.ramachandran@colorado.edu
*
*  Main script parser/logic interface of the game. Do not edit this file unless 
*  absolutely necessary
* 
*
*  This project is under the GNU General GPL version 3.0 license. For more 
*  information about the license, refer the LICENCE file in the root directory 
*  or go online to <http://www.gnu.org/licenses>
*  
*  Any redistribution of this code must contain this header in its entirety
*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "kardinal.h"

int Free_var(VariableDec * Vars){
	while(Vars!=NULL){
		free(Vars->value);
		VariableDec * tmp = Vars;
		Vars = Vars->prev;
		free(tmp);
	}
}

void print_variable_stack(VariableDec Vars){
	VariableDec * tmp = &Vars;
	printf("Debug : Printing current variable stack\n");
	while(tmp!=NULL){
		printf("Debug : %s : %s : %s : %d\n",tmp->varname,tmp->type,tmp->value,tmp->size);
		tmp=tmp->prev;
	}
	printf("\n");
}

